// src/server/auth/rbac/roles.ts
import { Permission } from './permissions';

export const ROLE_LEVELS: Record<string, number> = {
  master: 100,
  admin: 80,
  manager: 60,
  editor: 40,
  support: 30,
  accountant: 20,
  user: 10,
  viewer: 0,
} as const;

export type RoleName = keyof typeof ROLE_LEVELS;

export const ROLE_LABELS: Record<RoleName, string> = {
  master: 'Master',
  admin: 'Admin',
  manager: 'Manager',
  editor: 'Editor',
  support: 'Support',
  accountant: 'Accountant',
  user: 'User',
  viewer: 'Viewer',
};

export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  master: Object.values(Permission),
  admin: [
    Permission.USER_CREATE,
    Permission.USER_READ,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_LIST,
    Permission.ROLE_ASSIGN,
    Permission.ROLE_LIST,
    Permission.FILE_CREATE,
    Permission.FILE_READ,
    Permission.FILE_UPDATE,
    Permission.FILE_DELETE,
    Permission.FILE_SHARE,
    Permission.FILE_DOWNLOAD,
    Permission.FOLDER_CREATE,
    Permission.FOLDER_READ,
    Permission.FOLDER_UPDATE,
    Permission.FOLDER_DELETE,
    Permission.SHARE_CREATE,
    Permission.SHARE_READ,
    Permission.SHARE_UPDATE,
    Permission.SHARE_DELETE,
    Permission.ADMIN_PANEL,
    Permission.SYSTEM_SETTINGS,
    Permission.AUDIT_READ,
  ],
  manager: [
    Permission.USER_READ,
    Permission.USER_LIST,
    Permission.FILE_CREATE,
    Permission.FILE_READ,
    Permission.FILE_UPDATE,
    Permission.FILE_DELETE,
    Permission.FILE_SHARE,
    Permission.FILE_DOWNLOAD,
    Permission.FOLDER_CREATE,
    Permission.FOLDER_READ,
    Permission.FOLDER_UPDATE,
    Permission.FOLDER_DELETE,
    Permission.SHARE_CREATE,
    Permission.SHARE_READ,
    Permission.SHARE_UPDATE,
    Permission.SHARE_DELETE,
    Permission.AUDIT_READ,
  ],
  editor: [
    Permission.FILE_CREATE,
    Permission.FILE_READ,
    Permission.FILE_UPDATE,
    Permission.FILE_DELETE,
    Permission.FILE_SHARE,
    Permission.FILE_DOWNLOAD,
    Permission.FOLDER_CREATE,
    Permission.FOLDER_READ,
    Permission.FOLDER_UPDATE,
    Permission.FOLDER_DELETE,
    Permission.SHARE_CREATE,
    Permission.SHARE_READ,
  ],
  support: [
    Permission.USER_READ,
    Permission.USER_LIST,
    Permission.FILE_READ,
    Permission.FOLDER_READ,
    Permission.SHARE_READ,
    Permission.AUDIT_READ,
  ],
  accountant: [
    Permission.BILLING_VIEW,
    Permission.USER_READ,
    Permission.USER_LIST,
    Permission.AUDIT_READ,
  ],
  user: [
    Permission.FILE_CREATE,
    Permission.FILE_READ,
    Permission.FILE_UPDATE,
    Permission.FILE_DELETE,
    Permission.FILE_SHARE,
    Permission.FILE_DOWNLOAD,
    Permission.FOLDER_CREATE,
    Permission.FOLDER_READ,
    Permission.SHARE_CREATE,
    Permission.SHARE_READ,
  ],
  viewer: [
    Permission.FILE_READ,
    Permission.FOLDER_READ,
  ],
};
